#!/bin/bash                                                                                                                     

# Author; Raphael Udoh                                                                                                          

# Script for "I'M confused"                                                                                                     

echo "(Ôo)'   
